export const CURRENCIES = [
  { label: "الجنيه السوداني (SDG) ج.س", value: "SDG" },
  { label: "الريال السعودي (SAR) ر.س", value: "SAR" },
  { label: "الجنيه المصري (EGP) ج.م", value: "EGP" },
  { label: "الدرهم الإماراتي (AED) د.إ", value: "AED" },
  { label: "الدينار الكويتي (KWD) د.ك", value: "KWD" },
  { label: "الريال القطري (QAR) ر.ق", value: "QAR" },
  { label: "الدينار البحريني (BHD) د.ب", value: "BHD" },
  { label: "الريال العماني (OMR) ر.ع", value: "OMR" },
  { label: "الدينار الأردني (JOD) د.أ", value: "JOD" },
  { label: "الليرة اللبنانية (LBP) ل.ل", value: "LBP" },
  { label: "الدينار العراقي (IQD) د.ع", value: "IQD" },
  { label: "الليرة السورية (SYP) ل.س", value: "SYP" },
  { label: "الشيقل الفلسطيني (ILS) ₪", value: "ILS" },
  { label: "الدرهم المغربي (MAD) د.م.", value: "MAD" },
  { label: "الدينار التونسي (TND) د.ت", value: "TND" },
  { label: "الدينار الجزائري (DZD) د.ج", value: "DZD" },
  { label: "الدينار الليبي (LYD) ل.د", value: "LYD" },
  { label: "الدولار الأمريكي (USD) $", value: "USD" },
  { label: "اليورو (EUR) €", value: "EUR" },
  { label: "الجنيه الإسترليني (GBP) £", value: "GBP" },
  { label: "الين الياباني (JPY) ¥", value: "JPY" },
  { label: "اليوان الصيني (CNY) ¥", value: "CNY" },
  { label: "الروبية الهندية (INR) ₹", value: "INR" },
  { label: "الدولار الأسترالي (AUD) A$", value: "AUD" },
  { label: "الدولار الكندي (CAD) C$", value: "CAD" },
  { label: "الفرنك السويسري (CHF) CHF", value: "CHF" },
  { label: "الكرونة السويدية (SEK) kr", value: "SEK" },
  { label: "الكرونة النرويجية (NOK) kr", value: "NOK" },
  { label: "الكرونة الدنماركية (DKK) kr", value: "DKK" },
  { label: "الروبل الروسي (RUB) ₽", value: "RUB" },
  { label: "الليرة التركية (TRY) ₺", value: "TRY" },
  { label: "الريال البرازيلي (BRL) R$", value: "BRL" },
  { label: "البيزو المكسيكي (MXN) $", value: "MXN" },
  { label: "الراند الجنوب أفريقي (ZAR) R", value: "ZAR" },
  { label: "البيزو الفلبيني (PHP) ₱", value: "PHP" },
  { label: "الدولار السنغافوري (SGD) S$", value: "SGD" },
  { label: "الدولار الهونغ كونغي (HKD) HK$", value: "HKD" },
  { label: "الوون الكوري الجنوبي (KRW) ₩", value: "KRW" },
  { label: "الروبية الإندونيسية (IDR) Rp", value: "IDR" },
  { label: "الرينغيت الماليزي (MYR) RM", value: "MYR" },
  { label: "البات التايلاندي (THB) ฿", value: "THB" },
  { label: "الدونغ الفيتنامي (VND) ₫", value: "VND" },
  { label: "البيزو التشيلي (CLP) $", value: "CLP" },
  { label: "البيزو الكولومبي (COP) $", value: "COP" },
  { label: "البيزو الأرجنتيني (ARS) $", value: "ARS" },
  { label: "السول البيروفي (PEN) S/", value: "PEN" },
  { label: "البيزو الأوروغواياني (UYU) $U", value: "UYU" },
  { label: "النافكا الإريترية (ERN) Nfk", value: "ERN" },
  { label: "البر الإثيوبي (ETB) Br", value: "ETB" },
  { label: "الشلن الكيني (KES) KSh", value: "KES" },
  { label: "الشلن الأوغندي (UGX) USh", value: "UGX" },
  { label: "الشلن التنزاني (TZS) TSh", value: "TZS" },
  { label: "الشلن الصومالي (SOS) S", value: "SOS" },
  { label: "الفرنك الرواندي (RWF) FRw", value: "RWF" },
  { label: "الفرنك البوروندي (BIF) FBu", value: "BIF" },
  { label: "الفرنك الجيبوتي (DJF) Fdj", value: "DJF" },
  { label: "النيرا النيجيرية (NGN) ₦", value: "NGN" },
  { label: "السيدي الغاني (GHS) GH₵", value: "GHS" },
  { label: "الفرنك الوسط أفريقي (XAF) FCFA", value: "XAF" },
  { label: "الفرنك الغرب أفريقي (XOF) CFA", value: "XOF" },
  { label: "الكوانزا الأنجولي (AOA) Kz", value: "AOA" },
  { label: "الميتيكال الموزمبيقي (MZN) MT", value: "MZN" },
  { label: "البولا البوتسواني (BWP) P", value: "BWP" },
  { label: "الليلانغيني السوازيلندي (SZL) L", value: "SZL" },
  { label: "اللوتي الليسوتي (LSL) L", value: "LSL" },
  { label: "الدولار الناميبي (NAD) N$", value: "NAD" },
  { label: "الكواشا الزامبي (ZMW) ZK", value: "ZMW" },
  { label: "الكواشا المالاوي (MWK) MK", value: "MWK" },
  { label: "الدولار الزيمبابوي (ZWL) Z$", value: "ZWL" },
];
